import type { Language, Question, QuizCopy } from "@/lib/quiz-types";

export const LANGUAGE_STORAGE_KEY = "pilates-health-quiz-language";
export const AUTH_STORAGE_KEY = "pilates-health-quiz-auth";
export const AUTH_ACCOUNTS_STORAGE_KEY = "pilates-health-quiz-accounts";

export const copy = {
  en: {
    loading: "Loading your quiz...",
    brandEyebrow: "Pilates Health Assessment",
    heroTitle: "A calmer way into a stronger body.",
    heroSub:
      "Answer a few focused questions and unlock a beginner Pilates plan shaped around your current body, goal, and rhythm.",
    heroBadge: "Private health assessment in under a minute",
    language: "Language",
    savedAnswers: "Saved answers",
    requiredFields: "Health fields",
    session: "Session",
    notStarted: "not started",
    quizLabel: "Health assessment",
    selected: "Selected",
    choose: "Choose",
    continue: "Continue",
    back: "Back",
    saved: "Saved",
    syncIdle: "Saved securely after each answer",
    syncing: "Syncing in background...",
    synced: "Synced",
    syncError: "Kept on this device. Sync needs retry.",
    finishingSync: "Finishing sync...",
    result: "Result",
    step: "Step",
    rangeError: (min: number, max: number) =>
      `Enter a value between ${min} and ${max}.`,
    restoreError: "We could not restore your previous quiz.",
    createError: "Could not create your quiz session.",
    saveError: "Could not save your answer.",
    missingAnswer: "Please complete the remaining questions first.",
    completeError: "Could not complete the quiz.",
    resultError: "Could not load your result.",
    paymentError: "Payment simulation failed.",
    reviewEyebrow: "Profile ready",
    reviewTitle: "Your wellness profile is ready to calculate.",
    editAnswers: "Edit answers",
    seeResult: "See my result",
    calculating: "Calculating...",
    planUnlocked: "Plan unlocked",
    profilePreview: "Wellness profile",
    unlockedTitle: "Your beginner Pilates plan is unlocked.",
    lockedTitle: "Here is your preview.",
    bmi: "BMI",
    category: "Category",
    calories: "Daily calories",
    bmr: "BMR",
    tdee: "TDEE",
    targetDate: "Target date",
    projection: "Weight projection",
    reportTitle: "Fat-loss cycle report",
    mildCut: "Mild cut",
    standardCut: "Standard cut",
    weeks: "weeks",
    impossible: "Not recommended",
    fullPlanLocked: "Full plan locked",
    defaultPaywall:
      "Your preview includes BMI and a basic health summary. Upgrade to unlock the full server-generated plan.",
    startOver: "Start over",
    resetQuiz: "Reset quiz",
    questionList: "Question list",
    remaining: "Remaining",
    completed: "Completed",
    current: "Current",
    upcoming: "Upcoming",
    next: "Next",
    answered: "Answered",
    unanswered: "Needs answer",
    optional: "Optional",
    jumpLocked: "Complete earlier steps first.",
    unlock: "Unlock full plan",
    unlocking: "Unlocking...",
    healthSnapshot: "Health snapshot",
    authEyebrow: "Start your quiz",
    authTitle: "Start with a secure health check",
    authLogin: "Log in",
    authRegister: "Register",
    authGuest: "Continue as guest",
    authName: "Name",
    authEmail: "Email",
    authPassword: "Password",
    authSubmitLogin: "Log in and continue",
    authSubmitRegister: "Create account and continue",
    authGuestNote: "Your progress will stay on this device.",
    authInvalid: "Please enter a valid email and password.",
    returnHome: "Home",
    accountGuest: "Guest",
    settings: "Settings",
    signIn: "Log in",
    logout: "Log out",
    upgradeMembership: "Upgrade membership",
  },
  zh: {
    loading: "正在载入你的测评...",
    brandEyebrow: "普拉提健康评估",
    heroTitle: "用更平静的方式，走向更强的身体。",
    heroSub:
      "回答几个关键问题，生成一份基于当前身体状态、目标和运动节奏的初学者普拉提计划。",
    heroBadge: "1 分钟完成隐私健康评估",
    language: "语言",
    savedAnswers: "已保存答案",
    requiredFields: "健康字段",
    session: "会话",
    notStarted: "尚未开始",
    quizLabel: "健康评估",
    selected: "已选择",
    choose: "选择",
    continue: "继续",
    back: "返回",
    saved: "已保存",
    syncIdle: "每题都会安全同步到当前会话",
    syncing: "后台同步中...",
    synced: "已同步",
    syncError: "当前设备已保留，同步需重试",
    finishingSync: "正在完成同步...",
    result: "结果",
    step: "第",
    rangeError: (min: number, max: number) => `请输入 ${min} 到 ${max} 之间的数值。`,
    restoreError: "无法恢复上次测评进度。",
    createError: "无法创建测评会话。",
    saveError: "无法保存你的答案。",
    missingAnswer: "请先完成剩余问题。",
    completeError: "无法完成测评。",
    resultError: "无法载入你的结果。",
    paymentError: "模拟支付失败。",
    reviewEyebrow: "档案已准备好",
    reviewTitle: "你的健康档案已经可以计算。",
    editAnswers: "修改答案",
    seeResult: "查看结果",
    calculating: "计算中...",
    planUnlocked: "计划已解锁",
    profilePreview: "健康档案",
    unlockedTitle: "你的初学者普拉提计划已解锁。",
    lockedTitle: "这是你的测评预览。",
    bmi: "BMI",
    category: "分类",
    calories: "每日热量",
    bmr: "基础代谢 BMR",
    tdee: "总消耗 TDEE",
    targetDate: "目标日期",
    projection: "体重预测",
    reportTitle: "减脂周期报告",
    mildCut: "温和减脂",
    standardCut: "标准减脂",
    weeks: "周",
    impossible: "不建议",
    fullPlanLocked: "完整计划已锁定",
    defaultPaywall:
      "当前预览包含 BMI 和基础健康摘要。升级会员后可解锁完整的服务端计算计划。",
    startOver: "重新开始",
    resetQuiz: "重置测评",
    questionList: "问题列表",
    remaining: "待完成",
    completed: "已完成",
    current: "当前",
    upcoming: "待解锁",
    next: "下一步",
    answered: "已回答",
    unanswered: "待回答",
    optional: "可选",
    jumpLocked: "请先完成前面的步骤。",
    unlock: "解锁完整计划",
    unlocking: "解锁中...",
    healthSnapshot: "健康概览",
    authEyebrow: "开始测评",
    authTitle: "从安全的健康评估开始",
    authLogin: "登录",
    authRegister: "注册",
    authGuest: "游客继续",
    authName: "姓名",
    authEmail: "邮箱",
    authPassword: "密码",
    authSubmitLogin: "登录并继续",
    authSubmitRegister: "创建账户并继续",
    authGuestNote: "进度会保存在当前设备上。",
    authInvalid: "请输入有效邮箱和密码。",
    returnHome: "主页",
    accountGuest: "游客",
    settings: "设置",
    signIn: "登录",
    logout: "退出登录",
    upgradeMembership: "充值会员",
  },
} satisfies QuizCopy;

export const answerLabels: Record<string, Record<Language, string>> = {
  "18-29": { en: "18-29", zh: "18-29 岁" },
  "30-39": { en: "30-39", zh: "30-39 岁" },
  "40-49": { en: "40-49", zh: "40-49 岁" },
  "50+": { en: "50+", zh: "50 岁以上" },
  female: { en: "Female", zh: "女性" },
  male: { en: "Male", zh: "男性" },
  other: { en: "Other", zh: "其他" },
  "Lose weight": { en: "Lose weight", zh: "减重" },
  "Increase muscle strength": { en: "Increase muscle strength", zh: "增强肌肉力量" },
  "Develop flexibility": { en: "Develop flexibility", zh: "提升柔韧性" },
  "Improve posture": { en: "Improve posture", zh: "改善体态" },
  sedentary: { en: "Never", zh: "几乎不运动" },
  light: { en: "Several times per month", zh: "每月几次" },
  moderate: { en: "Several times per week", zh: "每周几次" },
  active: { en: "Almost every day", zh: "几乎每天" },
  poorSleep: { en: "Often tired", zh: "经常疲惫" },
  fairSleep: { en: "Sometimes tired", zh: "偶尔疲惫" },
  goodSleep: { en: "Well rested", zh: "休息良好" },
  optionalUnsure: { en: "Not sure / skip", zh: "不清楚 / 跳过" },
  sittingLow: { en: "Under 4 hours", zh: "少于 4 小时" },
  sittingMedium: { en: "4-8 hours", zh: "4-8 小时" },
  sittingHigh: { en: "Over 8 hours", zh: "超过 8 小时" },
  concernPosture: { en: "Posture", zh: "体态" },
  concernBack: { en: "Back comfort", zh: "腰背舒适度" },
  concernCore: { en: "Core strength", zh: "核心力量" },
  concernFlexibility: { en: "Flexibility", zh: "柔韧性" },
  equipmentMat: { en: "Mat only", zh: "只有瑜伽垫" },
  equipmentProps: { en: "Small props", zh: "小器械" },
  equipmentReformer: { en: "Reformer access", zh: "有普拉提大器械" },
  beginner: { en: "Beginner", zh: "初学者" },
  returning: { en: "Returning after a break", zh: "中断后重新开始" },
  experienced: { en: "Experienced", zh: "有经验" },
  timeShort: { en: "Under 15 minutes", zh: "少于 15 分钟" },
  timeMedium: { en: "15-30 minutes", zh: "15-30 分钟" },
  timeLong: { en: "30+ minutes", zh: "30 分钟以上" },
  stressLow: { en: "Low", zh: "较低" },
  stressMedium: { en: "Moderate", zh: "中等" },
  stressHigh: { en: "High", zh: "较高" },
  limitationNone: { en: "No limitation", zh: "没有限制" },
  limitationKnee: { en: "Knee-sensitive", zh: "膝盖敏感" },
  limitationBack: { en: "Back-sensitive", zh: "腰背敏感" },
  limitationShoulder: { en: "Shoulder-sensitive", zh: "肩颈敏感" },
};

export const questions: Question[] = [
  {
    key: "ageRange",
    title: { en: "Select your age range to start", zh: "选择你的年龄段开始" },
    helper: {
      en: "Your plan begins with a short Pilates readiness check.",
      zh: "你的计划会从一个简短的普拉提准备度测评开始。",
    },
    type: "single",
    options: [
      { label: answerLabels["18-29"], value: "18-29" },
      { label: answerLabels["30-39"], value: "30-39" },
      { label: answerLabels["40-49"], value: "40-49" },
      { label: answerLabels["50+"], value: "50+" },
    ],
  },
  {
    key: "gender",
    title: { en: "Which option best describes you?", zh: "以下哪项更符合你？" },
    type: "single",
    options: [
      { label: answerLabels.female, value: "female" },
      { label: answerLabels.male, value: "male" },
      { label: answerLabels.other, value: "other" },
    ],
  },
  {
    key: "goal",
    title: { en: "What is your main goal?", zh: "你的主要目标是什么？" },
    type: "single",
    options: [
      { label: answerLabels["Lose weight"], value: "Lose weight" },
      { label: answerLabels["Increase muscle strength"], value: "Increase muscle strength" },
      { label: answerLabels["Develop flexibility"], value: "Develop flexibility" },
      { label: answerLabels["Improve posture"], value: "Improve posture" },
    ],
  },
  {
    key: "activityLevel",
    title: { en: "How often do you exercise?", zh: "你平时运动频率如何？" },
    type: "single",
    options: [
      { label: answerLabels.sedentary, value: "sedentary" },
      { label: answerLabels.light, value: "light" },
      { label: answerLabels.moderate, value: "moderate" },
      { label: answerLabels.active, value: "active" },
    ],
  },
  {
    key: "heightCm",
    title: { en: "How tall are you?", zh: "你的身高是多少？" },
    helper: { en: "Use centimeters for this version.", zh: "当前版本使用厘米作为单位。" },
    type: "number",
    suffix: { en: "cm", zh: "厘米" },
    min: 100,
    max: 250,
    placeholder: "165",
  },
  {
    key: "currentWeightKg",
    title: { en: "What is your current weight?", zh: "你现在的体重是多少？" },
    type: "number",
    suffix: { en: "kg", zh: "公斤" },
    min: 30,
    max: 300,
    placeholder: "80",
  },
  {
    key: "targetWeightKg",
    title: { en: "What is your goal weight?", zh: "你的目标体重是多少？" },
    helper: {
      en: "Choose a realistic target for a sustainable plan.",
      zh: "选择一个现实、可持续的目标。",
    },
    type: "number",
    suffix: { en: "kg", zh: "公斤" },
    min: 30,
    max: 300,
    placeholder: "70",
  },
  {
    key: "age",
    title: { en: "What is your exact age?", zh: "你的准确年龄是多少？" },
    type: "number",
    suffix: { en: "years", zh: "岁" },
    min: 13,
    max: 100,
    placeholder: "30",
  },
  {
    key: "sleepQuality",
    title: { en: "How rested do you usually feel?", zh: "你通常休息得怎么样？" },
    helper: {
      en: "Optional. This helps tune recovery and pacing recommendations.",
      zh: "可选。用于调整恢复和训练节奏建议。",
    },
    optional: true,
    type: "single",
    options: [
      { label: answerLabels.poorSleep, value: "poorSleep" },
      { label: answerLabels.fairSleep, value: "fairSleep" },
      { label: answerLabels.goodSleep, value: "goodSleep" },
      { label: answerLabels.optionalUnsure, value: "optionalUnsure" },
    ],
  },
  {
    key: "sittingHours",
    title: { en: "How long do you sit on a typical day?", zh: "你通常每天久坐多久？" },
    helper: {
      en: "Optional. Sitting time helps personalize posture and mobility work.",
      zh: "可选。久坐时长会影响体态和灵活性建议。",
    },
    optional: true,
    type: "single",
    options: [
      { label: answerLabels.sittingLow, value: "sittingLow" },
      { label: answerLabels.sittingMedium, value: "sittingMedium" },
      { label: answerLabels.sittingHigh, value: "sittingHigh" },
      { label: answerLabels.optionalUnsure, value: "optionalUnsure" },
    ],
  },
  {
    key: "bodyConcern",
    title: { en: "Which area should your plan pay extra attention to?", zh: "你希望计划额外关注哪一方面？" },
    helper: {
      en: "Optional. Choose the area that would make the plan feel most useful.",
      zh: "可选。选择最希望被照顾到的训练重点。",
    },
    optional: true,
    type: "single",
    options: [
      { label: answerLabels.concernPosture, value: "concernPosture" },
      { label: answerLabels.concernBack, value: "concernBack" },
      { label: answerLabels.concernCore, value: "concernCore" },
      { label: answerLabels.concernFlexibility, value: "concernFlexibility" },
      { label: answerLabels.optionalUnsure, value: "optionalUnsure" },
    ],
  },
  {
    key: "equipment",
    title: { en: "What Pilates equipment can you use?", zh: "你可以使用哪些普拉提器械？" },
    helper: {
      en: "Optional. This helps avoid recommending equipment you do not have.",
      zh: "可选。用于避免推荐你没有的器械训练。",
    },
    optional: true,
    type: "single",
    options: [
      { label: answerLabels.equipmentMat, value: "equipmentMat" },
      { label: answerLabels.equipmentProps, value: "equipmentProps" },
      { label: answerLabels.equipmentReformer, value: "equipmentReformer" },
      { label: answerLabels.optionalUnsure, value: "optionalUnsure" },
    ],
  },
  {
    key: "pilatesExperience",
    title: { en: "What is your Pilates experience level?", zh: "你的普拉提经验如何？" },
    helper: {
      en: "Optional. This helps tune difficulty and exercise progression.",
      zh: "可选。用于调整训练难度和动作进阶。",
    },
    optional: true,
    type: "single",
    options: [
      { label: answerLabels.beginner, value: "beginner" },
      { label: answerLabels.returning, value: "returning" },
      { label: answerLabels.experienced, value: "experienced" },
      { label: answerLabels.optionalUnsure, value: "optionalUnsure" },
    ],
  },
  {
    key: "sessionTime",
    title: { en: "How much time can you usually train per session?", zh: "你通常每次能训练多久？" },
    helper: {
      en: "Optional. This keeps the plan realistic for your schedule.",
      zh: "可选。用于让训练安排更贴近日常时间。",
    },
    optional: true,
    type: "single",
    options: [
      { label: answerLabels.timeShort, value: "timeShort" },
      { label: answerLabels.timeMedium, value: "timeMedium" },
      { label: answerLabels.timeLong, value: "timeLong" },
      { label: answerLabels.optionalUnsure, value: "optionalUnsure" },
    ],
  },
  {
    key: "stressLevel",
    title: { en: "How would you describe your current stress level?", zh: "你最近的压力水平如何？" },
    helper: {
      en: "Optional. Stress context helps balance intensity and recovery.",
      zh: "可选。压力状态会影响训练强度和恢复安排。",
    },
    optional: true,
    type: "single",
    options: [
      { label: answerLabels.stressLow, value: "stressLow" },
      { label: answerLabels.stressMedium, value: "stressMedium" },
      { label: answerLabels.stressHigh, value: "stressHigh" },
      { label: answerLabels.optionalUnsure, value: "optionalUnsure" },
    ],
  },
  {
    key: "movementLimitation",
    title: { en: "Any area that needs lower-impact options?", zh: "有没有需要低冲击替代动作的部位？" },
    helper: {
      en: "Optional. This is not medical advice, but it helps avoid aggressive suggestions.",
      zh: "可选。这不是医疗建议，但能帮助避免过激训练推荐。",
    },
    optional: true,
    type: "single",
    options: [
      { label: answerLabels.limitationNone, value: "limitationNone" },
      { label: answerLabels.limitationKnee, value: "limitationKnee" },
      { label: answerLabels.limitationBack, value: "limitationBack" },
      { label: answerLabels.limitationShoulder, value: "limitationShoulder" },
      { label: answerLabels.optionalUnsure, value: "optionalUnsure" },
    ],
  },
];
