import type { Language, Question, QuizCopy } from "@/lib/quiz-types";

export const SESSION_STORAGE_KEY = "pilates-health-quiz-session-id";
export const LANGUAGE_STORAGE_KEY = "pilates-health-quiz-language";

export const copy = {
  en: {
    loading: "Loading your quiz...",
    brandEyebrow: "Pilates Health Quiz",
    heroTitle: "A calmer way into a stronger body.",
    heroSub:
      "Answer a few focused questions and unlock a beginner Pilates plan shaped around your current body, goal, and rhythm.",
    heroBadge: "Personalized in under a minute",
    language: "Language",
    savedAnswers: "Saved answers",
    requiredFields: "Health fields",
    session: "Session",
    notStarted: "not started",
    quizLabel: "1-minute quiz",
    selected: "Selected",
    choose: "Choose",
    continue: "Continue",
    back: "Back",
    saved: "Saved",
    syncIdle: "Saved locally after each answer",
    syncing: "Syncing in background...",
    synced: "Synced",
    syncError: "Saved locally. Sync needs retry.",
    finishingSync: "Finishing sync...",
    result: "Result",
    step: "Step",
    rangeError: (min: number, max: number) =>
      `Enter a value between ${min} and ${max}.`,
    restoreError: "We could not restore your previous quiz.",
    createError: "Could not create your quiz session.",
    saveError: "Could not save your answer.",
    missingAnswer: "Please complete the remaining questions first.",
    completeError: "Could not complete the quiz.",
    resultError: "Could not load your result.",
    paymentError: "Payment simulation failed.",
    reviewEyebrow: "Profile ready",
    reviewTitle: "Your wellness profile is ready to calculate.",
    editAnswers: "Edit answers",
    seeResult: "See my result",
    calculating: "Calculating...",
    planUnlocked: "Plan unlocked",
    profilePreview: "Wellness profile",
    unlockedTitle: "Your beginner Pilates plan is unlocked.",
    lockedTitle: "Here is your preview.",
    bmi: "BMI",
    category: "Category",
    calories: "Daily calories",
    bmr: "BMR",
    tdee: "TDEE",
    targetDate: "Target date",
    projection: "Weight projection",
    reportTitle: "Fat-loss cycle report",
    mildCut: "Mild cut",
    standardCut: "Standard cut",
    weeks: "weeks",
    impossible: "Not recommended",
    fullPlanLocked: "Full plan locked",
    defaultPaywall: "Upgrade to unlock your full Pilates plan.",
    startOver: "Start over",
    resetQuiz: "Reset quiz",
    questionList: "Question list",
    remaining: "Remaining",
    completed: "Completed",
    current: "Current",
    upcoming: "Upcoming",
    next: "Next",
    answered: "Answered",
    unanswered: "Needs answer",
    jumpLocked: "Complete earlier steps first.",
    unlock: "Unlock full plan",
    unlocking: "Unlocking...",
    healthSnapshot: "Health snapshot",
  },
  zh: {
    loading: "正在载入你的测评...",
    brandEyebrow: "普拉提健康测评",
    heroTitle: "用更平静的方式，走向更强的身体。",
    heroSub:
      "回答几个关键问题，生成一份基于当前身体状态、目标和运动节奏的初学者普拉提计划。",
    heroBadge: "1 分钟内生成个性化计划",
    language: "语言",
    savedAnswers: "已保存答案",
    requiredFields: "健康字段",
    session: "会话",
    notStarted: "尚未开始",
    quizLabel: "1 分钟测评",
    selected: "已选择",
    choose: "选择",
    continue: "继续",
    back: "返回",
    saved: "已保存",
    syncIdle: "每题都会先保存到本地",
    syncing: "后台同步中...",
    synced: "已同步",
    syncError: "已本地保存，同步需重试",
    finishingSync: "正在完成同步...",
    result: "结果",
    step: "第",
    rangeError: (min: number, max: number) => `请输入 ${min} 到 ${max} 之间的数值。`,
    restoreError: "无法恢复上次测评进度。",
    createError: "无法创建测评会话。",
    saveError: "无法保存你的答案。",
    missingAnswer: "请先完成剩余问题。",
    completeError: "无法完成测评。",
    resultError: "无法载入你的结果。",
    paymentError: "模拟支付失败。",
    reviewEyebrow: "档案已准备好",
    reviewTitle: "你的健康档案已经可以计算。",
    editAnswers: "修改答案",
    seeResult: "查看结果",
    calculating: "计算中...",
    planUnlocked: "计划已解锁",
    profilePreview: "健康档案",
    unlockedTitle: "你的初学者普拉提计划已解锁。",
    lockedTitle: "这是你的测评预览。",
    bmi: "BMI",
    category: "分类",
    calories: "每日热量",
    bmr: "基础代谢 BMR",
    tdee: "总消耗 TDEE",
    targetDate: "目标日期",
    projection: "体重预测",
    reportTitle: "减脂周期报告",
    mildCut: "温和减脂",
    standardCut: "标准减脂",
    weeks: "周",
    impossible: "不建议",
    fullPlanLocked: "完整计划已锁定",
    defaultPaywall: "解锁后可查看完整普拉提计划。",
    startOver: "重新开始",
    resetQuiz: "重置测评",
    questionList: "问题列表",
    remaining: "待完成",
    completed: "已完成",
    current: "当前",
    upcoming: "待解锁",
    next: "下一步",
    answered: "已回答",
    unanswered: "待回答",
    jumpLocked: "请先完成前面的步骤。",
    unlock: "解锁完整计划",
    unlocking: "解锁中...",
    healthSnapshot: "健康概览",
  },
} satisfies QuizCopy;

export const answerLabels: Record<string, Record<Language, string>> = {
  "18-29": { en: "18-29", zh: "18-29 岁" },
  "30-39": { en: "30-39", zh: "30-39 岁" },
  "40-49": { en: "40-49", zh: "40-49 岁" },
  "50+": { en: "50+", zh: "50 岁以上" },
  female: { en: "Female", zh: "女性" },
  male: { en: "Male", zh: "男性" },
  other: { en: "Other", zh: "其他" },
  "Lose weight": { en: "Lose weight", zh: "减重" },
  "Increase muscle strength": { en: "Increase muscle strength", zh: "增强肌肉力量" },
  "Develop flexibility": { en: "Develop flexibility", zh: "提升柔韧性" },
  "Improve posture": { en: "Improve posture", zh: "改善体态" },
  sedentary: { en: "Never", zh: "几乎不运动" },
  light: { en: "Several times per month", zh: "每月几次" },
  moderate: { en: "Several times per week", zh: "每周几次" },
  active: { en: "Almost every day", zh: "几乎每天" },
};

export const questions: Question[] = [
  {
    key: "ageRange",
    title: { en: "Select your age range to start", zh: "选择你的年龄段开始" },
    helper: {
      en: "Your plan begins with a short Pilates readiness check.",
      zh: "你的计划会从一个简短的普拉提准备度测评开始。",
    },
    image: {
      src: "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=900&q=85",
      alt: { en: "Pilates mat setup in a calm studio", zh: "安静工作室里的普拉提垫" },
      caption: {
        en: "Age helps tune the pace and recovery rhythm.",
        zh: "年龄会帮助调整训练节奏和恢复安排。",
      },
    },
    type: "single",
    options: [
      { label: answerLabels["18-29"], value: "18-29" },
      { label: answerLabels["30-39"], value: "30-39" },
      { label: answerLabels["40-49"], value: "40-49" },
      { label: answerLabels["50+"], value: "50+" },
    ],
  },
  {
    key: "gender",
    title: { en: "Which option best describes you?", zh: "以下哪项更符合你？" },
    image: {
      src: "https://images.unsplash.com/photo-1571019613914-85f342c6a11e?auto=format&fit=crop&w=900&q=85",
      alt: {
        en: "Pilates class practicing controlled movement",
        zh: "普拉提课程中的控制训练",
      },
    },
    type: "single",
    options: [
      { label: answerLabels.female, value: "female" },
      { label: answerLabels.male, value: "male" },
      { label: answerLabels.other, value: "other" },
    ],
  },
  {
    key: "goal",
    title: { en: "What is your main goal?", zh: "你的主要目标是什么？" },
    image: {
      src: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=900&q=85",
      alt: {
        en: "Person stretching on a mat with soft light",
        zh: "柔和光线下在垫上伸展的人",
      },
      caption: {
        en: "Your goal shapes the tone of the recommendation.",
        zh: "目标会影响推荐计划的重点。",
      },
    },
    type: "single",
    options: [
      { label: answerLabels["Lose weight"], value: "Lose weight" },
      { label: answerLabels["Increase muscle strength"], value: "Increase muscle strength" },
      { label: answerLabels["Develop flexibility"], value: "Develop flexibility" },
      { label: answerLabels["Improve posture"], value: "Improve posture" },
    ],
  },
  {
    key: "activityLevel",
    title: { en: "How often do you exercise?", zh: "你平时运动频率如何？" },
    image: {
      src: "https://images.unsplash.com/photo-1518310383802-640c2de311b2?auto=format&fit=crop&w=900&q=85",
      alt: {
        en: "Fitness studio with exercise equipment",
        zh: "带有训练器械的健身空间",
      },
      caption: {
        en: "Activity level estimates daily energy needs.",
        zh: "运动频率会用于估算每日能量消耗。",
      },
    },
    type: "single",
    options: [
      { label: answerLabels.sedentary, value: "sedentary" },
      { label: answerLabels.light, value: "light" },
      { label: answerLabels.moderate, value: "moderate" },
      { label: answerLabels.active, value: "active" },
    ],
  },
  {
    key: "heightCm",
    title: { en: "How tall are you?", zh: "你的身高是多少？" },
    helper: { en: "Use centimeters for this version.", zh: "当前版本使用厘米作为单位。" },
    image: {
      src: "https://images.unsplash.com/photo-1576678927484-cc907957088c?auto=format&fit=crop&w=900&q=85",
      alt: { en: "Measuring tape and wellness notes", zh: "软尺和健康记录" },
      caption: {
        en: "Height lets us calculate BMI with better context.",
        zh: "身高会用于更准确地计算 BMI。",
      },
    },
    type: "number",
    suffix: { en: "cm", zh: "厘米" },
    min: 100,
    max: 250,
    placeholder: "165",
  },
  {
    key: "currentWeightKg",
    title: { en: "What is your current weight?", zh: "你现在的体重是多少？" },
    image: {
      src: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=900&q=85",
      alt: {
        en: "Training area with a scale and fitness mat",
        zh: "有体重秤和训练垫的运动区域",
      },
    },
    type: "number",
    suffix: { en: "kg", zh: "公斤" },
    min: 30,
    max: 300,
    placeholder: "80",
  },
  {
    key: "targetWeightKg",
    title: { en: "What is your goal weight?", zh: "你的目标体重是多少？" },
    helper: {
      en: "Choose a realistic target for a sustainable plan.",
      zh: "选择一个现实、可持续的目标。",
    },
    image: {
      src: "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=900&q=85",
      alt: {
        en: "Pilates movement focused on steady progress",
        zh: "强调稳定进步的普拉提动作",
      },
      caption: {
        en: "A realistic target keeps the plan sustainable.",
        zh: "现实目标能让计划更可持续。",
      },
    },
    type: "number",
    suffix: { en: "kg", zh: "公斤" },
    min: 30,
    max: 300,
    placeholder: "70",
  },
  {
    key: "age",
    title: { en: "What is your exact age?", zh: "你的准确年龄是多少？" },
    image: {
      src: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=900&q=85",
      alt: {
        en: "Pilates practitioner holding a balanced pose",
        zh: "普拉提练习者保持平衡姿势",
      },
    },
    type: "number",
    suffix: { en: "years", zh: "岁" },
    min: 13,
    max: 100,
    placeholder: "30",
  },
];
